### ISSUE TITLE
Notes’ title wrong capitalization 

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#12] opened 2021-06-09 05:10 UTC
The plugin automatically parses notes which do not preserve original title capitalization, but it capitalize exclusively the first letter of the whole title.

Some title examples:
- a note titled `The importance of RSS Feeds.md` appears as `The importance of rss feeds`
- a note titled `being Lucky.md` appears as `Being lucky`

Instead, title capitalization should be preserved.

Nevertheless, a note called `Hello world.md` and called as `[[Hello world|heLLo WoRLd]]` is correctly displayed as `heLLo WoRLd`.

**Comment by manunamz** [comment] 2021-06-23 13:31
Titles are rendered from the jekyll document's `title` data attribute. (See [here](https://github.com/manunamz/jekyll-wikilinks/blob/main/lib/jekyll-wikilinks.rb#L82)).

I imagine jekyll is doing this. Might want to double check how the `title` data attribute is being set, whether that is your note frontmatter's `title` attribute or somewhere in your configs.

**Comment by xplosionmind** [comment] 2021-06-23 18:54
> (See [here](https://github.com/manunamz/jekyll-wikilinks/blob/db2d25c91b558d49c023186bf0f07c1ba21d7095/lib/jekyll-wikilinks.rb#L82)).

I know no Ruby, but isn’t the `.downcase` addition that changes the behavior of how titles are parsed?  
Furthermore, most of the time I have no `title` specified in a file’s front matter, the name is retrieved from the name of the file.

**Comment by manunamz** [comment] 2021-06-23 21:15
`.downcase` should lowercase all letters, so if there are _any_ capitalized letters then that line is probably not producing that title's end result. I take this to mean that this plugin is not the cause of that capitalization...But I could be wrong.

How _exactly_ is the casing show up...? 
- ...in the wikilink? `[[being lucky]]` --rendering-as--> `Being lucky`
- ...in liquid tag? `{{ page.title }}` --rendering-as--> `Being lucky`
- ...or?

**Comment by xplosionmind** [comment] 2021-06-24 05:47
So… I was about to test the title capitalization to answer your last reply, but this came out of the blue at build time:

```
Configuration file: /Users/tommi/tommi.space/_config.yml
            Source: /Users/tommi/tommi.space
       Destination: /Users/tommi/tommi.space/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
bundler: failed to load command: jekyll (/Users/tommi/.rbenv/versions/3.0.1/bin/jekyll)
/Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:82:in `block in parse_wiki_links': undefined method `downcase' for nil:NilClass (NoMethodError)
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:71:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:71:in `parse_wiki_links'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:45:in `block in generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:44:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:44:in `generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:193:in `block in generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:43:in `block in profile_process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:41:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:41:in `profile_process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:75:in `process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/jekyll:23:in `load'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/jekyll:23:in `<top (required)>'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'
```

**Comment by xplosionmind** [comment] 2021-06-24 05:55
I do not understand the above mentioned problem. If it is going to be hard to fix, I will open a separate issue, but it appears to be somewhat related to the `.downcase` we were discussing. This happened out of the blue, the only thing I did was to update ffi from version 1.15.1 to 1.15.3.

**Comment by manunamz** [comment] 2021-06-25 17:50
Hmm...Ok. I will look into this more deeply.

In the meantime, I added a [test](https://github.com/manunamz/jekyll-wikilinks/blob/main/spec/jekyll-wikilinks/feature_vanilla_spec.rb#L70) to reflect what I expect to be happening, currently. (I didn't add it before because I was thinking of making capitalization behavior more robust/have-better-defaults-somehow).

**Comment by manunamz** [comment] 2021-06-25 18:15
Ha! Ok, so I guess that means you don't have the title metadata set anywhere? 🤔 I'm looking at [this](https://stackoverflow.com/a/18902079) SO comment. 
   
I will keep investigating...🧐💭

**Comment by xplosionmind** [comment] 2021-06-27 05:09
> you don't have the title metadata set anywhere?

Nope, I do not.

<br />

> I will keep investigating...🧐💭

Thank you very much! ❤️

**Comment by xplosionmind** [comment] 2021-06-27 05:12
> In the meantime, I added a test to reflect what I expect to be happening, currently.

So what should I do to avoid the build error?

**Comment by manunamz** [comment] 2021-06-27 20:14
Is this build error produced by your repo's current state? Can I clone the most [recent commit](https://github.com/xplosionmind/tommi.space) on the main branch to test it? And is it a local build or a netlify build?

**Comment by xplosionmind** [comment] 2021-07-01 20:26
> Is this build error produced by your repo's current state? Can I clone the most [recent commit](https://github.com/xplosionmind/tommi.space) on the main branch to test it? And is it a local build or a netlify build?

By updating to version 0.0.4, everything went away

**Comment by manunamz** [comment] 2021-07-03 20:29
> By updating to version 0.0.4, everything got back to normal

I'll close this then. Good to hear an update fixed it. 🎉

**Closed by manunamz** 2021-07-03 20:29 UTC

**Comment by xplosionmind** [comment] 2021-07-04 19:33
Actually, the error at build time is solved but the wrong capitalization is still happening…

I am sorry, I should have opened a new issue for the build error. Nevertheless, this issue is still relevant, @manunamz!
